# -*- coding: utf-8 -*-
"""Podcast_sammariser -- transcriptor using whisper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16PJkBv1Vqf-P_PsmfIOQ_TiYq2OEJtPg
"""

pip install gradio -q
pip install whisper
pip install openai-whisper -U
import whisper
from whisper.utils import WriteVTT

model = whisper.load_model("medium")

url = 'https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5zaW1wbGVjYXN0LmNvbS9kSG9vaFZOSA/episode/Y2M1NjEyYTMtMTc3MS00MmIxLTgyNzQtZmYxNWI3YWU5MGI2?sa=X&ved=0CAUQkfYCahgKEwioi4z4tOyDAxUAAAAAHQAAAAAQpAM'

import requests

content = requests.get(url)

from bs4 import BeautifulSoup
import re

soup = BeautifulSoup(content.text)

podcast_url = re.findall("(?P<url>\;https?://[^\s]+)", content.text)[0].split(';')[1]

podcast_url

wget -O podcast.mp3 {podcast_url}

result = model.transcribe('podcast.mp3',language='english')

with open('sub.vtt', "w") as txt:
  x=  WriteVTT(result)
  txt = WriteVTT(result)

with open('sub.vtt', "r") as txt:
 print('\n'.join(txt.readlines()))

result

import json
with open('sub.vtt', "w") as txt:
  json.dump(result, txt)

from whisper.utils import WriteVTT, WriteSRT,WriteJSON

writer = whisper.utils.get_writer("srt", "")
writer(result, "new.srt")

result['text']